.pre-commit-config.yaml, LICENSE, README.md, docs/README.md, pkg/schema.go, pkg/schema_test.go, plugin.yaml, testdata/anchors.schema.json, testdata/anchors.yaml
If `KeyNode` is `nil`, read from comments anyway.
Closes https://github.com/losisin/helm-values-schema-json/issues/28
=> Fix bug where keyNode is nil

.github/workflows/ci.yaml, docs/README.md, pkg/parser.go, pkg/parser_test.go, pkg/schema.go, pkg/schema_test.go, testdata/full.schema.json, testdata/full.yaml
closes [#32](https://github.com/losisin/helm-values-schema-json/issues/32)
=> add readOnly field to schema from comments

pkg/schema.go, pkg/schema_test.go, testdata/full.schema.json, testdata/full.yaml
Current behaviour is to read Items type only when array is not empty recursively from go types. Now it is possible to set Items type with schema annotation in comment.  Useful when array is empty but want to control the types accepted in array. 
closes #48
=> Set Items type in array with schema annotation

docs/README.md, pkg/schema.go, pkg/schema_test.go
This commit introduces a new feature that allows specifying enum values for array items in the JSON schema using the `itemEnum` annotation.
Changes:
- Update the `Schema` struct in `schema.go` to include a new `ItemsEnum` field to store the enum values for array items.
- Modify the `processComment` function in `schema.go` to handle the `item_enum` annotation and assign the enum values to the `Enum` field of the `Items` schema.
With this feature, users can now define enum values for array items in their YAML files using the `itemEnum` annotation, and the generated JSON schema will include the enum values within the `items` section.
Example:
```
capacityType: ["one","two"] # @schema type:[array];default:["one","two"];minItems:1;itemEnum:["one","two"]
```
Generated JSON for this value will …
=> Add: option to apply enum on array items

.goreleaser.yaml, .pre-commit-config.yaml, README.md, main.go, main_test.go, pkg/cmd.go, pkg/cmd_test.go, pkg/generator.go, pkg/generator_test.go, pkg/utils.go, pkg/utils_test.go, plugin.yaml, schema.yaml, values.schema.json
=> feature: read configuration from file

pkg/schema.go, pkg/schema_test.go, testdata/full.schema.json, testdata/full.yaml
@losisin Would you interested in merging a feature like this ?
Usecase:
```
labels:
default:
app.k8s.io:/name: abc
app.k8s.io/namespace: def
```
Ideally, in this case I would only want labels.default to be an object, and not have any  properties as the yaml is completely a user input blob, and can have any properties
So adding `skipProperties: true` here would not those in schema
=> chore: add option to skip properties for a node

pkg/schema.go, pkg/schema_test.go, testdata/full.schema.json, testdata/full.yaml
=> feature: set properties in object

docs/README.md
The `item` annotation was added in #49, but README.md was not updated.
=> docs: Add documentation for `item` annotation and fix typos

README.md, pkg/cmd.go, pkg/cmd_test.go, pkg/generator.go, pkg/generator_test.go, pkg/parser.go, pkg/parser_test.go, pkg/schema.go, pkg/utils.go, testdata/noAdditionalProperties.schema.json, testdata/noAdditionalProperties.yaml
This will default `additionalProperties` to `false` for all objects in the schema if set to `true`. The `additionalProperties` annotation, `schemaRoot.additionalProperties` and additionalProperties set via other ways (nested in `itemProperties`, `patternProperties` or similar) will take precedence over this setting, so it's fully backwards compatible.
Closes #95.
=> feat: introduce flag noAdditionalProperties

pkg/schema.go
When sequence node has items that are arrays, we assumed that those arrays have same set of elements so only the first item was analysed. Now, that is no longer the case and all those arrays are merged into single one before determining their types.
closes #99
=> feature: merge nested arrays

docs/README.md, pkg/parser.go, pkg/parser_test.go, pkg/schema.go, pkg/schema_test.go, testdata/subschema.schema.json, testdata/subschema.yaml
subschema keywords supported:
- `allOf`
- `anyOf`
- `oneOf`
- `not`
NOTE: when subschema keywords are used, the `"type"` filed is dropped from the generated schema. You MUST add it as part of the required array and valid schema for the keyword
closes #110
=> feature: add subschema keywords

pkg/bundle.go, pkg/bundle_test.go, pkg/pointer.go, pkg/pointer_test.go, pkg/schema.go
This actually tackles multiple bugs:
- when loaded subschema has `$defs` with `$id`, then move those to the root schema
- when loaded subschema has `$ref: #/...`, and using `-bundleWithoutID`, then change it to `$ref: #/$defs/loaded.json/...`
- I forgot to go through `/items` when iterating subschemas
In the process I also added `Ptr` type that is a [JSON pointer](https://datatracker.ietf.org/doc/html/rfc6901), which is the syntax used in `$ref: #/...` URL fragments. They have a special encoding of `/` and `~` that we need to escape. This also slightly changes the error message. Maybe we want to use this in `convertSchemaToMap` too to give better hint at what part is having an error?
Some changes were also applied because I use [gofumpt](https://github.com/mvdan/gofumpt), like the …
=> Fix `-bundleWithoutID` when subschema has local inline references

pkg/schema.go, pkg/schema_test.go
Fixes the case where this:
```yaml
hello: # ; enum: dooblip
```
was parsed as:
- `enum:dooblip`
And as another example, this:
```yaml
hello: # foo:bar; moo:doo; maz:daz
```
was parsed as:
- `moo:doo`
- `maz:daz`
With this PR it doesn't get parsed at all.
It also fixes so `#@schema` and `#\t@schema` are parsed correctly
Closes #152
=> Fix parser not requiring `@schema` prefix

docs/README.md, pkg/schema.go, pkg/schema_test.go, testdata/full.yaml
Now if I read you correctly, then this feature might be a little controversial.
Implementation wise, this is quite simple.
However I saw two counter-arguments:
When I was testing helm-docs, it was possible to work around it so it doesn't collide. Helm-docs does not error when it sees `@schema` comments, so it's fully possible to have them co-exist.
You have to make sure you put the `@schema` comments above the helm-docs `# -- my description` comment, which is less nice. But at least it is possible.
The schema comments does pollute the comment space for when skimming comments and makes it harder to read.
However the foot comments help with that. So instead of this:
```yaml
pullPolicy: IfNotPresent
```
then you could do this:
```yaml
pullPolicy: IfNotPresent
```
which does move the schema …
=> Add support for head & foot comments

go.mod, main.go
This assumes the next version is going to be v2.0.0
Go has their odd versioning scheme thing, so if someone wants to do `go install` on this project and the Git tag is v2.x.x then it has to be under this "fake `/v2/` path"
=> Prepare Go module path for v2

.schema.yaml, pkg/bundle.go, pkg/bundle_test.go, pkg/cmd.go, pkg/generator.go, pkg/generator_test.go, pkg/pointer.go, pkg/pointer_test.go, testdata/bundle/simple-root-ref.schema.json, testdata/doc.go
There was an issue when using bundling together with schema root refs from config or flags.
This attempts to fix it by doing some `filepath.Rel` operations, so that what you define as schema root ref via config or flags are relative to current working directory, but then that gets translated on each file to be relative to the file. This is because the FileLoader reads this relative to the file's directory.
Closes #159
=> Fix bundling with $ref on schema root (for v1)

Makefile
Allows me to run `make` on my NixOS computer, as NixOS doesn't have bash at `/bin/bash`, but it does have `/usr/bin/env`
=> Fix /bin/bash -> /usr/bin/env bash in Makefile

pkg/bundle.go, pkg/bundle_test.go
Shows different units depending on size.
This is mostly to prevent it from showing `0KB` when file is below 1 KB
The threshold to switch from B to KB at 2 KB is completely arbitrary. I just felt like showing something like `1200B` is better than `1KB`
=> Format loaded bytes with B, KB, and MB

.schema.yaml
Fixes the `.schema.yaml` file in the `v1` branch.
Now `go test .` works
I fixed this in #167 for the `main` branch, but in this PR I'm backporting it to the `v1` branch
=> chore: Fix .schema.yaml in v1 branch

pkg/cmd.go, pkg/generator_test.go, pkg/schema.go, pkg/schema_test.go
Changes `interface{}` to `any`
This "modernizes" this syntax.
In my PRs I've been using `any`, and so now the code base uses both `interface{}` and `any`. So to normalize it, I suggest changing all uses to `any`
=> chore: Change `interface{}` to `any`

.gitignore, .goreleaser.yaml, main.go, main_test.go, pkg/cmd.go, pkg/cmd_test.go, pkg/loader.go, pkg/loader_test.go
- Changed goreleaser to use `v{{ .Version }}` instead of `v{{ .Tag }}` so it includes the snapshot suffix, if any (basically only matters when running goreleaser locally)
- Set command version from either:
- goreleaser, when building with goreleaser
- main module version, when installing using `go install github.com/...@latest`
- or lastly from version-control info, when building using `go build`
- Show version using `--version` flag
- Show version using `version` subcommand
- Use version in HTTPLoader User-Agent
Closes #184
=> feat: show version with `--version` flag or `version` subcommand

README.md, docs/upgrading.md, docs/upgrading/v1.9-to-v2.0.md, docs/upgrading/v1.x.x-to-v2.0.0.md
Adds docs on upgrade notes. I copied the style from etcd because I liked what they did with the diffs: <https://etcd.io/docs/v3.6/upgrades/upgrade_3_6/>
I suggest we edit the v2.0.0 release notes on GitHub releases (once published) to include a link to this.
Other changes:
- Added link to upgrade docs in README
- Changed code blocks in README to not have `$` prefix, as it makes the snippets easier to copy-paste
- Some other misc changes to the repo README.md
Closes #180
=> docs: Upgrade notes for v1 -> v2.0.0

.github/workflows/ci.yaml, README.md
Changes:
- Run CI on `main` branch
- Run CI on all PRs instead of only those that target the `main` branch
- Change badge to only show results from `main` branch
Two main motivations for running CI on the `main` branch:
- Then the badge won't show "failing" just because tests in a PR is failing
- Running CI on the `main` branch populates the cache. The GitHub Action cache is not shared between all branches. It only reuses the cache if the cache was created on the same branch or the default branch. Meaning any newly created PR doesn't use any cache at all.
=> chore: Run CI on `main` branch & all PRs

pkg/bundle.go, pkg/bundle_test.go, pkg/cmd.go, pkg/generator.go, pkg/generator_test.go, pkg/loader.go, pkg/loader_test.go, pkg/log.go, pkg/log_test.go
Adds logger interface that allows using `testing.T.Log` during tests, but uses `os.Stdout` in normal execution.
Now when 1 test fails, you won't get all the output from the other tests anymore, which makes it much more readable. This will help when debugging #191 
Added bonus is that the logs in the test results show which line caused the log:
```
=== RUN   TestHTTPLoader_Cache/sends_new_request_if_etag_save_fails
loader.go:266: Loading http://127.0.0.1:35741
loader.go:313: Error using etag cache: dummy error
loader.go:366: Error saving response cache: dummy error
loader.go:376: => got 2B in 0s
```
Closes #182
=> chore: Added logger to improve test output

docs/README.md, internal/testutil/testutil.go, internal/testutil/testutil_test.go, pkg/bundle_test.go, pkg/comment.go, pkg/comment_test.go, pkg/generator.go, pkg/parser.go, pkg/parser_test.go, pkg/schema.go, pkg/schema_test.go
I started with making boolean annotations allow empty strings, but then I started flowing and my changes grew, and grew, and grew. I didn't make intermediate commits, so everything is just bunched up into a single commit.
So instead of just boolean annotations, this PR reworks the comment parsing a bit. Changes:
- BREAKING: Schema comment parsing now errors instead of silently ignoring
- on invalid value, e.g `# @schema readOnly: 123`
- and on unknown annotation key, e.g `# @schema foobar: 123`
- Boolean annotations now allow skipping the `true` part, which then implicitly means `true`. For example, these two are now semantically identical:
```yaml
```
- Now supports YAML syntax instead of just JSON syntax in more places. For example, these two are now semantically identical:
```yaml
``` …
=> feat: Schema comment parsing errors & better parsing

.github/workflows/release.yaml
goreleaser warns about us using `latest` in the workflow. They suggest sticking to `~> v2` so that we don't automatically update to v3 and break our builds
=> Fix goreleaser build warning

docs/README.md, pkg/loader.go
Kubernetes has developed a new config language called KYAML: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/5295-kyaml
It's just a slimmed down version of YAML. Pure subset.
Our bundler checks the file extension on local files to figure out which parser to use. This PR just adds `.kyaml` & `.kyml` to the list of YAML file extensions.
=> feat: support '.kyaml' extension when bundling local files

.github/workflows/auto-approve-dependabot.yml
Tries to fix the workflow.
I don't think these changes are actually why it failed. But it doesn't hurt to remove my GitHub Enterprise stuff and to use `secrets.GITHUB_TOKEN` as advised by the [docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request) instead of `github.token` (should be the same though...)
=> chore: Fix auto-approve workflow
